FROM golang:alpine as base
RUN apk add --no-cache ca-certificates git
WORKDIR /backend
COPY go.* ./
RUN go mod download

FROM base as build
COPY . .
RUN go build -o server main.go

FROM alpine as prod
EXPOSE 8000
RUN apk add --no-cache libc6-compat ca-certificates
COPY --from=build /backend/server /backend/
CMD ["/backend/server"]
