version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: tn
      POSTGRES_PASSWORD: dtnDb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgbouncer:
    depends_on:
      - db
    image: brainsam/pgbouncer
    restart: always
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: dtnDb
      DB_PORT: 5432
    ports:
      - 6432:6432
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
      target: prod
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: ./log
        target: /log