version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: tn
      POSTGRES_PASSWORD: dtnDb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgbouncer:
    depends_on:
      - db
    image: brainsam/pgbouncer
    restart: always
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: dtnDb
      DB_PORT: 5432
    ports:
      - 6432:6432

  app-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: dev
    restart: always
    ports:
      - 40000:40000
      - 8000:8080
    security_opt:
      - "seccomp:unconfined" # Extra option to allow debugging.
    cap_add:
      - SYS_PTRACE # Recommended option for debugging only.
